# -*- coding: utf-8 -*-
"""healthcare_it_asset_triage.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1m6kMVqnEPHB0QfjrrkSdk_SEbJ-ZAlQX
"""

# CyberSecurity Asset Triage

# This notebook is a practice execrise for
# reviewing a fictional device intentory. It demostrates
# Markdown, Python code cells, output, simple filtering,
# and an AI-assisted learning workflow

devices = [
    {"name": "ER-WS-12", "type": "Windows workstation", "os": "Windows 11",
     "days_since_patch": 12, "encrypted": True},
    {"name": "Nurse-TAB-04", "type": "Tablet", "os": "Andriod", "days_since_patch": 47,
     "encrypted": True},
    {"name": "LAB-WS-03", "type": "Windows Workstation", "os": "Windows 10", "days_since_patch": 95,
     "encrypted": False},
    {"name": "IMAGING-01", "type": "Imaging console", "os": "Vendor appliance", "days_since_patch": 160,
     "encrypted": True},
     {"name": "IMAGING-04", "type": "Cell Phone", "os": "iOS", "days_since_patch": 60,
     "encrypted": False},
]
print(f"Loaded {len(devices)} fictional devices.")

for device in devices:
  print(device["name"], "-", device["os"], "-",
device["days_since_patch"], "days since patch")

needs_attention = []

for device in devices:
  if device["days_since_patch"] > 60 or device["encrypted"] == False:
    needs_attention.append(device)

print(f"Devices needing review: {len(needs_attention)}")
for device in needs_attention:
  print('-', device["name"])